# Use a base image with necessary tools and libraries
FROM ubuntu:latest

# Set the working directory inside the container
WORKDIR /autodock-vina-build

# Update the package index and install necessary dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        libboost-all-dev \
        swig \
        git \
        wget \
    && rm -rf /var/lib/apt/lists/(*) #use * w/o brackets

# Clone the AutoDock Vina repository from GitHub
RUN git config --global http.sslVerify false
RUN git clone https://github.com/ccsb-scripps/AutoDock-Vina /autodock-vina

# Build AutoDock Vina
RUN cd /autodock-vina \
    && cd build/linux/release \
    #&& cmake -DCMAKE_BUILD_TYPE=Release .. \
    && make

# Add the vina binary to the PATH for easy execution
ENV PATH="/autodock-vina/build/linux/release:${PATH}"

# Set the entrypoint to vina for easy execution
ENTRYPOINT ["vina"]

# Set the default command (e.g., --help) when running the container without additional arguments
CMD ["--help"]
